name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux
          - os: ubuntu-24.04-arm
            platform: linux
          - os: macos-14
            platform: darwin
          - os: windows-2022
            platform: win32
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm test
